version: '2'

services:

  varnish:
    image: eeacms/varnish
    ports:
    - "80:6081"
    volumes:
      - "./varnish/:/etc/varnish/conf.d/"
    networks:
    - web
    env_file:
      - "./common/environment"

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./mysql/data/:/var/lib/mysql/"
    env_file:
      - "./common/environment"
      - "./mysql/environment"

  ezpublish:
    image: jakubsacha/symfony-docker:php5
    ports:
      - "81:80"
    volumes:
      - "./apache/apache2:/usr/local/bin/apache2-start"
      - "./apache/www/:/var/www/html/"
    command: /usr/local/bin/apache2-start
    env_file:
      - "./common/environment"
    links:
      - mysql
    networks:
      - web

networks:
  web:
