parameters:
    secret: 2472ff5cdde1ace5a4a13d29a5a9644f1663fdfe
    locale_fallback: en
    mailer_transport: smtp
    mailer_host: mx-gw.infrawan.net
    mailer_user: null
    mailer_password: null
    static_html_bundles:
        default: ProjectBundle
    database_driver: pdo_mysql
    database_host: mysql
    database_port: null
    database_name: ezpublish
    database_user: ezpublish
    database_password: ezpublish
    image_magic_root: /usr/bin/convert
