_statichtml:
    resource: "@KaliopStaticHtmlBundle/Resources/config/routing.yml"

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

# Symfony 2.6
#_errors:
#    resource: "@TwigBundle/Resources/config/routing/errors.xml"
#    prefix:   /_error

_main:
    resource: routing.yml

#static_html:
#    resource: "@KaliopStaticHtmlBundle/Resources/config/routing.yml"
